Assignment/urls.py
from django.urls import path

from Assignment import views
from Assignment.views import LoginView, RegisterView, AssignmentView, StudentAssignmentListView, \
    SubmissionView, MarkAssignmentView, SubmitAssignmentView, ProfileView, ForgotPasswordView, ChangePasswordView, \
    AdminView

app_name = 'Assignment'

urlpatterns = [
    path("", LoginView.as_view(), name="login"),
    path("logout", views.log_out, name="logout"),
    path("register", RegisterView.as_view(), name="register"),
    path("forgot_password", ForgotPasswordView.as_view(), name="forgot_password"),
    path("forgot_password/<int:id>/change_password", ChangePasswordView.as_view(), name="change_password"),
    path("assignment", AssignmentView.as_view(), name="assignment"),
    path("assignment/<int:ass_id>/students", StudentAssignmentListView.as_view(), name="student_assignment_list"),
    path("assignment/<int:id>/submission", SubmissionView.as_view(), name="submission"),
    path("assignment/<int:sub_id>/submission/mark_assignment", MarkAssignmentView.as_view(), name="mark_assignment"),
    path("assignment/<int:ass_id>/submission/submit_assignment", SubmitAssignmentView.as_view(),
         name="submit_assignment"),
    path("profile", ProfileView.as_view(), name="profile"),
    path("profile/admin", AdminView.as_view(), name="profile_admin"),
    path("profile/admin/add_course", views.add_course, name="add_course"),
]

AssignmentSystem/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from AssignmentSystem import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("Assignment.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Assignment/models.py
from django.contrib.auth.models import User
from django.db import models


class Person(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    last_name = models.CharField(max_length=50)
    first_name = models.CharField(max_length=50)
    email = models.EmailField()

    def __str__(self):
        return f'{self.last_name} {self.first_name}'


class Student(models.Model):
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    matric_no = models.CharField(max_length=20)

    def __str__(self):
        return self.matric_no


class Staff(models.Model):
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    staff_id = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.person}"


class Course(models.Model):
    title = models.CharField(max_length=100)
    code = models.CharField(max_length=10)
    lecturer = models.ForeignKey(Staff, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.code}"


class Assignment(models.Model):
    title = models.CharField(max_length=100)
    file = models.FileField(upload_to='Assignment/files')
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    lecturer = models.ForeignKey(Staff, on_delete=models.CASCADE)
    date_given = models.DateTimeField()
    deadline = models.DateTimeField()

    def __str__(self):
        return f"{self.title}"


class Grading(models.Model):
    assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    score = models.IntegerField(default=0)
    feedback = models.CharField(max_length=500)

    def __str__(self):
        return f"{self.score}"


class Submission(models.Model):
    assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    grading = models.ForeignKey(Grading, on_delete=models.CASCADE)
    text = models.CharField(max_length=1000)
    file = models.FileField(upload_to='Assignment/submission')
    date = models.DateField()

    def __str__(self):
        return f"{self.student}"


class RegisteredCourses(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    courses = models.ManyToManyField(Course)

    def __str__(self):
        return f"{self.student}"


class RegisteredStudents(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    students = models.ManyToManyField(Student)

    def __str__(self):
        return f"{self.course}"

Assignment/views.py
from datetime import datetime

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import View

from Assignment.functions import upload_student, upload_course, upload_staff
from Assignment.models import Person, Student, Staff, Course, Assignment, Submission, RegisteredCourses, Grading, \
    RegisteredStudents


class LoginView(View):
    template_name = "Assignment/login.html"

    def get(self, request):
        # Go to the register page
        return render(request, self.template_name)

    def post(self, request):
        # Check if form is submitting
        if request.method == "POST":
            # Collect inputs
            username = request.POST.get("username").strip()
            password = request.POST.get("password")

            # Authenticate user
            user = authenticate(username=username, password=password)

            # Check if user exist
            if user is not None:
                # Login user
                login(request, user)
                # Redirect to learning page
                return HttpResponseRedirect(reverse("Assignment:assignment"))
            else:
                # Send error message
                messages.error(request, "Invalid credentials")
                # Redirect to login page
                return HttpResponseRedirect(reverse("Assignment:login"))


class RegisterView(View):
    template_name = "Assignment/register.html"

    def get(self, request):
        # Go to the register page
        return render(request, self.template_name)

    def post(self, request):
        # Check if form is submitting
        if request.method == "POST":
            # Collect inputs
            file = request.FILES.get('file')
            file_type = request.POST.get('type')

            if file_type == "student":
                try:
                    upload_student(file)
                except Exception:
                    messages.error(request, "Error uploading file")
                    return HttpResponseRedirect(reverse("Assignment:register"))
            elif file_type == "staff":
                try:
                    upload_staff(file)
                except Exception:
                    messages.error(request, "Error uploading file")
                    return HttpResponseRedirect(reverse("Assignment:register"))
            elif file_type == "course":
                try:
                    upload_course(file)
                except Exception:
                    messages.error(request, "Error uploading file")
                    return HttpResponseRedirect(reverse("Assignment:register"))

            messages.success(request, "File upload successful")
            return HttpResponseRedirect(reverse("Assignment:login"))


class ForgotPasswordView(View):
    template_name = "Assignment/forgot_password.html"

    def get(self, request):
        # Go to the register page
        return render(request, self.template_name)

    def post(self, request):
        # Check if form is submitting
        if request.method == "POST":
            # Collect inputs
            username = request.POST.get("username").strip()

            if User.objects.filter(username=username).exists():
                user = User.objects.get(username=username)
                person = Person.objects.get(user=user)
                return HttpResponseRedirect(reverse("Assignment:change_password", args=(person.id,)))
            else:
                messages.error(request, "User does not exist")
                return HttpResponseRedirect(reverse("Assignment:forgot_password"))


class ChangePasswordView(View):
    template_name = "Assignment/change_password.html"

    def get(self, request, id):
        # Go to the register page
        return render(request, self.template_name)

    def post(self, request, id):
        person = Person.objects.get(id=id)
        # Check if form is submitting
        if request.method == "POST":
            # Collect inputs
            password = request.POST.get("password").strip()
            confirm_password = request.POST.get("confirm_password").strip()

            if password == confirm_password:
                person.user.set_password(password)
                person.user.save()
                messages.success(request, "Password update successful")
                return HttpResponseRedirect(reverse("Assignment:login"))
            else:
                messages.error(request, "Password does not match")
                return HttpResponseRedirect(reverse("Assignment:change_password", args=(person.id,)))


class AssignmentView(View):
    template_name = "Assignment/assignment.html"

    @method_decorator(login_required)
    def get(self, request):
        person = Person.objects.get(user=request.user)

        if Staff.objects.filter(person=person).exists():
            lecturer = Staff.objects.get(person=person)
            all_assignments = Assignment.objects.filter(lecturer=lecturer)
            courses = Course.objects.filter(lecturer=lecturer)
            current_user = "staff"
            return render(request, self.template_name,
                          {'assignments': all_assignments, "user": current_user, "person": person, "courses": courses})

        else:
            student = Student.objects.get(person=person)
            reg_courses = RegisteredCourses.objects.get(student=student)
            all_assignments = [
                Assignment.objects.filter(course=course).values() for course in reg_courses.courses.all()
            ]
            all_assignments = [
                {"id": ass[0]["id"], "title": ass[0]["title"],
                 "course": Course.objects.get(id=ass[0]["course_id"]).code, "date_given": ass[0]["date_given"],
                 "deadline": ass[0]["deadline"]} for ass in all_assignments
            ]
            current_user = "student"

            return render(request, self.template_name,
                          {'assignments': all_assignments, "user": current_user, "person": person})

    @method_decorator(login_required)
    def post(self, request):
        person = Person.objects.get(user=request.user)
        lecturer = Staff.objects.get(person=person)
        # Check if form is submitting
        if request.method == "POST":
            # Collect inputs
            course_code = request.POST.get("course_code").strip().upper()
            pdf_title = request.POST.get("pdf_title").strip().upper()
            deadline = request.POST.get("deadline")
            file = request.FILES.get("file")
            print(file)

            course = Course.objects.get(code=course_code)
            Assignment.objects.create(title=pdf_title, file=file, course=course, lecturer=lecturer,
                                      date_given=datetime.now().today(), deadline=deadline)

            # Redirect back to register page
            return HttpResponseRedirect(reverse("Assignment:assignment"))


class StudentAssignmentListView(View):
    template_name = "Assignment/student_assignment_list.html"

    @method_decorator(login_required)
    def get(self, request, ass_id):
        person = Person.objects.get(user=request.user)
        assignment = Assignment.objects.get(id=ass_id)
        all_submission = Submission.objects.filter(assignment=assignment)
        return render(request, self.template_name, {"all_submission": all_submission, "person": person})


class SubmissionView(View):
    template_name = "Assignment/submission.html"

    @method_decorator(login_required)
    def get(self, request, id):
        person = Person.objects.get(user=request.user)

        if Staff.objects.filter(person=person).exists():
            lecturer = Staff.objects.get(person=person)
            current_user = "staff"
            submission = Submission.objects.get(id=id)
            return render(request, self.template_name,
                          {"submission": submission, "user": current_user, "person": person})

        else:
            student = Student.objects.get(person=person)
            current_user = "student"
            assignment = Assignment.objects.get(id=id)
            if Submission.objects.filter(**{"assignment": assignment, "student": student}).exists():
                submission = Submission.objects.get(assignment=assignment, student=student)
                return render(request, self.template_name,
                              {"submission": submission, "user": current_user, "person": person})
            else:
                return render(request, self.template_name,
                              {"assignment": assignment, "user": current_user, "person": person})


class MarkAssignmentView(View):
    template_name = "Assignment/mark_assignment.html"

    @method_decorator(login_required)
    def get(self, request, sub_id):
        person = Person.objects.get(user=request.user)
        submission = Submission.objects.get(id=sub_id)
        return render(request, self.template_name, {"submission": submission, "person": person})

    @method_decorator(login_required)
    def post(self, request, sub_id):
        submission = Submission.objects.get(id=sub_id)

        # Check if form is submitting
        if request.method == "POST":
            # Collect inputs
            score = request.POST.get("score").strip()
            feedback = request.POST.get("feedback").strip()

            submission.grading.score = score
            submission.grading.feedback = feedback
            submission.grading.save()

            return HttpResponseRedirect(reverse("Assignment:submission", args=(submission.id,)))


class SubmitAssignmentView(View):

Assignment/templates/Assignment/assignment.html
{% extends 'account-nav.html' %}

{% load static %}

{% block title %}
Assignment
{% endblock title %}

{% block body %}
    
<!-- COURSE CONCERN -->
<section id="course-concern" class="course-concern">
    <div class="container">

        <div class="table-asignment">

            <ul class="nav-tabs" role="tablist">
                <li class="active"><a href="#assignment" role="tab" data-toggle="tab">Assignments</a></li>
                {% if user == "staff" %}
                <li><a href="#addassignment" role="tab" data-toggle="tab">Add Assignment</a></li>
                {% endif %}
            </ul>

            <!-- Tab panes -->
            <div class="tab-content">
                <!-- ASSIGNMENTS -->
                <div class="tab-pane fade in active" id="assignment">
                    <div class="table-wrap">
                        <!-- TABLE HEAD -->
                        <div class="table-head">
                            <div class="latest-reply">Title</div>
                            <div class="tb-icon">Course</div>
                            <div class="latest-reply">Date Given</div>
                            <div class="latest-reply">Deadline</div>
                            <div class="latest-reply"></div>
                        </div>
                        <!-- END / TABLE HEAD -->

                        <!-- TABLE BODY -->
                        <div class="table-body">
                            <!-- TABLE ITEM -->
                            <div class="table-item">
                                {% for ass in assignments %}
                                <div class="thead">
                                    <div class="latest-reply">{{ ass.title }}</div>
                                    <div class="tb-icon">{{ ass.course }}</div>
                                    <div class="latest-reply">{{ ass.date_given }}</div>
                                    <div class="latest-reply">{{ ass.deadline }}</div>
                                    <div class="latest-reply">
                                        {% if user == 'staff' %}
                                        <a class="btn btn-primary" style="color:white" href="{% url 'Assignment:student_assignment_list' ass.id %}">View Assignment</a>
                                        {% else %}
                                        <a class="btn btn-primary" style="color:white" href="{% url 'Assignment:submission' ass.id%}">View Assignment</a>
                                        {% endif %}
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                            <!-- END / TABLE ITEM -->

                        </div>
                        <!-- END / TABLE BODY -->
                    </div>

                </div>
                <!-- END / ASSIGNMENTS -->

                {% if user == "staff" %}
                <!-- ADD ASSIGNMENT -->
                <div class="tab-pane fade" id="addassignment">
                    <div class="table-wrap">
                        <form method="post" action="" class="avatar-acount" style="width:fit-content" enctype="multipart/form-data">
                        {% csrf_token %}
                            <h3>New Assignment</h3>
                            <p>Fill in the form to add assignment</p>
                            <div class="">
                                <select class="form-control" name="course_code" required>
                                    <option value="">Choose Course Code</option>
                                    {% for course in courses %}
                                    <option value="{{ course.code }}">{{ course.code }}</option>
                                    {% endfor %}
                                </select><br>
                                <input class="form-control" type="text" name="pdf_title" placeholder="PDF Title" required><br>
                                <small>Add deadline date<span style="color:red">*</span></small><br>
                                <input class="form-control" type="date" name="deadline" required><br>
                                <input class="form-control" type="file" name="file" required><br>
                            </div>
                            <div class="input-save">
                                <input type="submit" value="Submit" class="mc-btn btn-style-1">
                            </div>
                        </form>
                    </div>
                </div>
                <!-- END / ADD ASSIGNMENT -->
                {% endif %}
            </div>

        </div>
    </div>
</section>
<!-- END / COURSE CONCERN -->

{% endblock body %}

Assignment/templates/Assignment/change_password.html
{% extends 'auth.html' %}

{% load static %}

{% block title %}
Change Password
{% endblock title %}

{% block main %}

{% block auth_list %}
<li class="menu-item-has-children current-menu-item">
    <a href="{% url 'Assignment:login' %}">Login</a>
    <ul class="sub-menu">
        <li class="current-menu-item"><a href="{% url 'Assignment:login' %}">Login</a></li>
        <li><a href="{% url 'Assignment:register' %}">Register</a></li>
    </ul>
</li>
{% endblock auth_list %}

{% block form %}

 <!-- FORM -->
<div class="col-xs-12 col-lg-4 pull-right">
    <div class="form-login">
        <form action="" method="post">
            {% csrf_token %}
            <h2 class="text-uppercase">Change Password</h2>

            {% for message in messages %}
            <div role="alert" aria-live="assertive" aria-atomic="true" class="toast {% if message.tags == 'success' %}
                    bg-success
                    {% else %}
                    bg-danger
                    {% endif %}" data-autohide="false">
              <div class="toast-header">
                <strong class="mr-auto">
                    {% if message.tags == 'success' %}
                    Success
                    {% else %}
                    Error
                    {% endif %}
                </strong>
                <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="toast-body">
                {{ message }}
              </div>
            </div>
            {% endfor %}

            <div class="form-password">
                <input type="password" name="password" placeholder="New Password" required>
            </div>
            <div class="form-password">
                <input type="password" name="confirm_password" placeholder="Confirm Password" required>
            </div>
            <div class="form-submit-1">
                <input type="submit" value="Submit" class="mc-btn btn-style-1">
            </div>
        </form>
    </div>
</div>
<!-- END / FORM -->
{% endblock form %}

{% endblock main %}

Assignment/templates/Assignment/forgot_password.html
{% extends 'auth.html' %}

{% load static %}

{% block title %}
Forgot Password
{% endblock title %}

{% block main %}

{% block auth_list %}
<li class="menu-item-has-children current-menu-item">
    <a href="{% url 'Assignment:login' %}">Login</a>
    <ul class="sub-menu">
        <li class="current-menu-item"><a href="{% url 'Assignment:login' %}">Login</a></li>
        <li><a href="{% url 'Assignment:register' %}">Register</a></li>
    </ul>
</li>
{% endblock auth_list %}

{% block form %}

 <!-- FORM -->
<div class="col-xs-12 col-lg-4 pull-right">
    <div class="form-login">
        <form action="" method="post">
            {% csrf_token %}
            <h2 class="text-uppercase">Forgot Password</h2>

            {% for message in messages %}
            <div role="alert" aria-live="assertive" aria-atomic="true" class="toast {% if message.tags == 'success' %}
                    bg-success
                    {% else %}
                    bg-danger
                    {% endif %}" data-autohide="false">
              <div class="toast-header">
                <strong class="mr-auto">
                    {% if message.tags == 'success' %}
                    Success
                    {% else %}
                    Error
                    {% endif %}
                </strong>
                <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="toast-body">
                {{ message }}
              </div>
            </div>
            {% endfor %}

            <div class="form-email">
                <input type="text" name="username" placeholder="Username" required>
            </div>
            <div class="form-submit-1">
                <input type="submit" value="Submit" class="mc-btn btn-style-1">
            </div>
        </form>
    </div>
</div>
<!-- END / FORM -->
{% endblock form %}

{% endblock main %}

Assignment/templates/Assignment/profile_admin.html
{% extends 'account-nav.html' %}

{% load static %}

{% block title %}
Assignment
{% endblock title %}

{% block body %}
    
<!-- COURSE CONCERN -->
<section id="course-concern" class="course-concern">
    <div class="container">

        <div class="table-asignment">

            <ul class="nav-tabs" role="tablist">
                <li class="active"><a href="#courses" role="tab" data-toggle="tab">Courses</a></li>
                {% if user == "staff" %}
                <li><a href="#staffreg" role="tab" data-toggle="tab">Register Course</a></li>
                {% else %}
                <li><a href="#studentadd" role="tab" data-toggle="tab">Add Course</a></li>
                {% endif %}
            </ul>

            <!-- Tab panes -->
            <div class="tab-content">
                <!-- ASSIGNMENTS -->
                <div class="tab-pane fade in active" id="courses">
                    <div class="table-wrap">
                        <!-- TABLE HEAD -->
                        <div class="table-head">
                            <div class="submissions">Course Title</div>
                            <div class="total-subm">Course Code</div>
                        </div>
                        <!-- END / TABLE HEAD -->

                        <!-- TABLE BODY -->
                        <div class="table-body">
                            <!-- TABLE ITEM -->
                            <div class="table-item">
                                {% for course in all_courses %}
                                <div class="thead">
                                    <div class="submissions">{{ course.title }}</div>
                                    <div class="total-subm">{{ course.code }}</div>
                                </div>
                                {% endfor %}
                            </div>
                            <!-- END / TABLE ITEM -->

                        </div>
                        <!-- END / TABLE BODY -->
                    </div>

                </div>
                <!-- END / ASSIGNMENTS -->

                {% if user == "staff" %}
                <!-- ADD ASSIGNMENT -->
                <div class="tab-pane fade" id="staffreg">
                    <div class="table-wrap">
                        <form method="post" action="" class="avatar-acount" style="width:fit-content">
                        {% csrf_token %}
                            <h3>Register New Course</h3>
                            <p>Fill in the form to register for the new course</p>
                            <div class="">
                                <input class="form-control" type="text" name="course_title" placeholder="Course Title" required><br>
                                <input class="form-control" type="text" name="course_code" placeholder="Course Code" required><br>
                            </div>
                            <div class="input-save">
                                <input type="submit" value="Register" class="mc-btn btn-style-1">
                            </div>
                        </form>
                    </div>
                </div>
                <!-- END / ADD ASSIGNMENT -->
                {% else %}
                <!-- ADD ASSIGNMENT -->
                <div class="tab-pane fade" id="studentadd">
                    <div class="table-wrap">
                        <form method="post" action="{% url 'Assignment:add_course' %}" class="avatar-acount" style="width:fit-content">
                        {% csrf_token %}
                            <h3>Add Course</h3>
                            <p>Enter the course code of the course you want to do</p>
                            <div class="">
                                <input class="form-control" type="text" name="course_code" placeholder="Course Code" required><br>
                            </div>
                            <div class="">
                                <input type="submit" value="Add" class="mc-btn btn-style-1">
                            </div>
                        </form>
                    </div>
                </div>
                <!-- END / ADD ASSIGNMENT -->
                {% endif %}
            </div>

        </div>
    </div>
</section>
<!-- END / COURSE CONCERN -->

{% endblock body %}

Assignment/templates/Assignment/submission.html
{% extends 'account-nav.html' %}

{% load static %}

{% block title %}
Assignment Submission
{% endblock title %}

{% block body %}

<section id="quizz-intro-section" class="quizz-intro-section learn-section">
        <div class="container">

            <div class="title-ct">
                <h3><strong>Title</strong>
                {% if submission %}
                    {{ submission.assignment.title }}
                {% else %}
                    {{ assignment.title }}
                {% endif %}
                </h3>
            </div>

            <div class="question-content-wrap">
                <div class="row">
                    <div class="col-md-8">
                        <div class="question-content">
                            {% if submission %}
                            <h4 class="sm bold">Answer</h4>
                            <p>{{ submission.text }}</p>

                            <h4 class="sm bold">Feedback</h4>
                            <ul class="list-disc">
                                <li>{{ submission.grading.feedback }}</li>
                            </ul>

                            {% else %}
                            <h4 class="sm bold">Warning</h4>
                            <p>Assignment must be submitted before {{ assignment.deadline }}</p>

                            <div class="download-file-learn">
                                <a href="{% url 'Assignment:submit_assignment' assignment.id %}" class="mc-btn btn-style-1">
                                    <i class="icon md-download-1"></i>
                                    Submit Assignment
                                </a>
                            </div>
                            {% endif %}
                        </div>
                    </div>


                    <div class="col-md-4">
                        <aside class="question-sidebar">
                            <div class="download-file-learn">
                                {% if submission %}
                                <a href="/media/{{ submission.assignment.file }}" class="mc-btn btn-style-1" download>
                                    <i class="icon md-download-1"></i>
                                    Assignment File
                                </a>
                                {% else %}
                                <a href="/media/{{ assignment.file }}" class="mc-btn btn-style-1" download>
                                    <i class="icon md-download-1"></i>
                                    Assignment File
                                </a>
                                {% endif %}
                            </div>
                            <div class="score-sb">
                                <h4 class="title-sb">Total score<span>
                                    {% if submission %}
                                    {{ submission.grading.score }}
                                    {% else %}
                                    0
                                    {% endif %}
                                </span></h4>
                            </div>

                            {% if user == 'staff' %}
                            {% if submission.grading.score <= 0 %}
                            <div class="download-file-learn">
                                <a href="{% url 'Assignment:mark_assignment' submission.id %}" class="mc-btn btn-style-1">
                                    Mark Assignment
                                </a>
                            </div>
                            {% endif %}
                            {% endif %}
                        </aside>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock body %}