Assignment/urls.py
from django.urls import path

from Assignment import views
from Assignment.views import LoginView, RegisterView, AssignmentView, StudentAssignmentListView, \
    SubmissionView, MarkAssignmentView, SubmitAssignmentView, ProfileView, ForgotPasswordView, ChangePasswordView, \
    AdminView

app_name = 'Assignment'

urlpatterns = [
    path("", LoginView.as_view(), name="login"),
    path("logout", views.log_out, name="logout"),
    path("register", RegisterView.as_view(), name="register"),
    path("forgot_password", ForgotPasswordView.as_view(), name="forgot_password"),
    path("forgot_password/<int:id>/change_password", ChangePasswordView.as_view(), name="change_password"),
    path("assignment", AssignmentView.as_view(), name="assignment"),
    path("assignment/<int:ass_id>/students", StudentAssignmentListView.as_view(), name="student_assignment_list"),
    path("assignment/<int:id>/submission", SubmissionView.as_view(), name="submission"),
    path("assignment/<int:sub_id>/submission/mark_assignment", MarkAssignmentView.as_view(), name="mark_assignment"),
    path("assignment/<int:ass_id>/submission/submit_assignment", SubmitAssignmentView.as_view(),
         name="submit_assignment"),
    path("profile", ProfileView.as_view(), name="profile"),
    path("profile/admin", AdminView.as_view(), name="profile_admin"),
    path("profile/admin/add_course", views.add_course, name="add_course"),
]

AssignmentSystem/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from AssignmentSystem import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("Assignment.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/account-nav.html
{% extends 'base.html' %}

{% load static %}

{% block nav %}
<!-- NAVIGATION -->
<nav class="navigation" style="padding: 30px">
</nav>
<!-- END / NAVIGATION -->
{% endblock nav %}

{% block content %}

    <!-- PROFILE FEATURE -->
    <section class="profile-feature">
        <div class="awe-parallax bg-profile-feature"></div>
        <div class="awe-overlay overlay-color-3"></div>
        <div class="container">
            <div class="info-author">
                <div class="image">
                    <img src="Fresh/IMG-20220102-WA0018.jpg" alt="" width="70px">
                </div>
                <div class="name-author">
                    <h2 class="big">{{ person.last_name }} {{ person.first_name }}</h2>
                </div>
                <div class="address-author">
                    <i class="fa fa-map-marker"></i>
                    <h3>DOMINION UNIVERSITY</h3>
                </div>
            </div>

        </div>
    </section>
    <!-- END / PROFILE FEATURE -->

     <!-- CONTENT BAR -->
    <section class="content-bar">
        <div class="container">
            <ul>
                <li>
                    <a href="{% url 'Assignment:assignment' %}">
                        <i class="icon md-shopping"></i>
                        Assignment
                    </a>
                </li>
                <li>
                    <a href="{% url 'Assignment:profile' %}">
                        <i class="icon md-user-minus"></i>
                        Profile
                    </a>
                </li>
                <li>
                    <a href="{% url 'Assignment:profile_admin' %}">
                        <i class="icon md-email"></i>
                        Admin
                    </a>
                </li>
                <li>
                    <a href="{% url 'Assignment:logout' %}">
                        <i class="icon md-arrow-right"></i>
                        Logout
                    </a>
                </li>
            </ul>
        </div>
    </section>
   <!-- END / CONTENT BAR -->

    {% block body %}
    {% endblock body %}

{% endblock content %}

templates/auth.html
{% extends 'base.html' %}

{% load static %}


{% block nav %}
<!-- NAVIGATION -->
<nav class="navigation">
    <!-- MENU -->
    <ul class="menu">
        {% block auth_list %}
        {% endblock auth_list %}
    </ul>
    <!-- END / MENU -->

</nav>
<!-- END / NAVIGATION -->
{% endblock nav %}

{% block content %}

<!-- LOGIN -->
<section id="login-content" class="login-content">
    <div class="awe-parallax bg-login-content"></div>
    <div class="awe-overlay"></div>
    <div class="container">
        <div class="row">

            {% block form %}
            {% endblock form %}

            <div class="image">
                <img src="images/homeslider/img-thumb.png" alt="">
            </div>

        </div>
    </div>
</section>
<!-- END / LOGIN -->

{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="format-detection" content="telephone=no">
    <!-- Google font -->
    <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Raleway:300,400,700,900' rel='stylesheet' type='text/css'>
    <!-- Css -->
    <link rel="stylesheet" type="text/css" href="{% static 'Assignment/css/library/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'Assignment/css/library/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'Assignment/css/library/owl.carousel.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'Assignment/css/md-font.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'Assignment/css/style.css' %}">

    <title>{% block title %}{% endblock title %} | Assignment System</title>
</head>
<body id="page-top" class="home">

<!-- PAGE WRAP -->
<div id="page-wrap">

    <!-- PRELOADER -->
    <div id="preloader">
        <div class="pre-icon">
            <div class="pre-item pre-item-1"></div>
            <div class="pre-item pre-item-2"></div>
            <div class="pre-item pre-item-3"></div>
            <div class="pre-item pre-item-4"></div>
        </div>
    </div>
    <!-- END / PRELOADER -->

    <!-- HEADER -->
    <header id="header" class="header">
        <div class="container">

            <!-- LOGO -->
            <div class="logo"><a href="{% url 'Assignment:login' %}"><img src="{% static 'Assignment/images/IMG-20221003-WA0000-removebg-preview.png' %}" alt="" width="70px">DU ASSIGNMENT PORTAL</a></div>
            <!-- END / LOGO -->

            {% block nav %}
            {% endblock nav %}

        </div>
    </header>
    <!-- END / HEADER -->

    {% block content %}
    {% endblock content %}

    <!-- FOOTER -->
    <footer id="footer" class="footer">
        <div class="first-footer">
            <div class="container">
                <div class="row">

                    <div class="col-md-3">
                        <div class="widget megacourse">
                            <h3 class="md">Dominion University</h3>
                            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat</p>
                            <a href="#" class="mc-btn btn-style-1">Get started</a>
                        </div>
                    </div>

                    <div class="col-md-3">
                        <div class="widget widget_latest_new">
                            <h3 class="sm">Latest News</h3>
                            <ul>
                                <li>
                                    <a href="#">
                                        <div class="image-thumb">
                                            <img src="images/team-13.jpg" alt="">
                                        </div>
                                        <span>Puga Commences?</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <div class="image-thumb">
                                            <img src="images/team-13.jpg" alt="">
                                        </div>
                                        <span>Student vacate?</span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>

                    <div class="col-md-2">
                        <div class="widget quick_link">
                            <h3 class="sm">Quick Links</h3>
                            <ul class="list-style-block">
                                <li><a href="#">About us</a></li>
                                <li><a href="#">Terms of use</a></li>
                                <li><a href="#">FAQ</a></li>
                                <li><a href="#">Support</a></li>
                                <li><a href="#">Contact</a></li>
                            </ul>
                        </div>
                    </div>

                    <div class="col-md-4">
                        <div class="widget news_letter">
                            <div class="awe-static bg-news_letter"></div>
                            <div class="overlay-color-3"></div>
                            <div class="inner">
                                <div class="letter-heading">
                                    <h3 class="md">News letter</h3>
                                    <p>Don’t miss a course sale! Join our network today and keep it up!</p>
                                </div>
                                <div class="letter">
                                    <form>
                                        <input class="input-text" type="text">
                                        <span class="no-spam">* No spam guaranteed</span>
                                        <input type="submit" value="Submit now" class="mc-btn btn-style-2">
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>

        <div class="second-footer">
            <div class="container">
                <div class="contact">
                    <div class="email">
                        <i class="icon md-email"></i>
                        <a href="#">olaoluwanioseni@gmail.com</a>
                    </div>
                    <div class="phone">
                        <i class="fa fa-mobile"></i>
                        <span>+2349025920717</span>
                    </div>
                    <div class="address">
                        <i class="fa fa-map-marker"></i>
                        <span>Dominion University</span>
                    </div>
                </div>
                <p class="copyright">Copyright © 2023 Oseni Olaoluwani Isreal & Ariyo-Olaitan Samson. All rights reserved.</p>
            </div>
        </div>
    </footer>
    <!-- END / FOOTER -->


</div>
<!-- END / PAGE WRAP -->

<!-- Load jQuery -->
<script type="text/javascript" src="{% static 'Assignment/js/library/jquery-1.11.0.min.js' %}"></script>
<script type="text/javascript" src="{% static 'Assignment/js/library/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'Assignment/js/library/jquery.owl.carousel.js' %}"></script>
<script type="text/javascript" src="{% static 'Assignment/js/library/jquery.appear.min.js' %}"></script>
<script type="text/javascript" src="{% static 'Assignment/js/library/perfect-scrollbar.min.js' %}"></script>
<script type="text/javascript" src="{% static 'Assignment/js/library/jquery.easing.min.js' %}"></script>
<script type="text/javascript" src="{% static 'Assignment/js/scripts.js' %}"></script>
<script type="text/javascript" src="{% static 'Assignment/js/main.js' %}"></script>
</body>

</html>